packages:
    - 'packages/*'
    - 'apps/*'

catalog:
    '@primeuix/styled': ^0.7.4
    '@primeuix/utils': ^0.7.2
    '@primeuix/styles': ^2.0.3
    '@primeuix/themes': ^2.0.3
    '@primeuix/motion': ^0.0.10
    '@primeuix/mcp': ^1.0.0
    'tailwindcss-primeui': ^0.6.1
    'primeicons': ^7.0.0

catalogs:
    angular22:
        "@angular-devkit/build-angular": ^22.0.0
        "@angular/cdk": ^22.0.0
        "@angular/cli": ^22.0.0
        "@angular/common": ^22.0.0
        "@angular/compiler": ^22.0.7
        "@angular/compiler-cli": ^22.0.0
        "@angular/core": ^22.0.7
        "@angular/forms": ^22.0.0
        "@angular/platform-browser": ^22.0.0
        "@angular/platform-browser-dynamic": ^22.0.0
        "@angular/platform-server": ^22.0.0
        "@angular/router": ^22.0.0
        "@angular/ssr": ^22.0.0
        "@angular-eslint/eslint-plugin": ^22.1.0
        "@angular-eslint/eslint-plugin-template": ^22.1.0
        "@angular-eslint/schematics": ^22.1.0
        "@angular-eslint/template-parser": ^22.1.0
        "ng-packagr": 22.0.1
        "typescript": 6.0.3
